### ISSUE TITLE
Digital Images: The property digitally_shown_by is not defined in representation

### ISSUE THREAD

**Issue by burki** [linked-art/json-validator#4]
When I try to validate the example from https://linked.art/model/digital/ below, I get the message:

[representation[0]] The property digitally_shown_by is not defined and the definition does not allow additional properties

`{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/person/15",
  "type": "Person",
  "_label": "E.G. Person",
  "representation": [
    {
      "type": "VisualItem",
      "digitally_shown_by": [
        {
          "type": "DigitalObject",
          "_label": "Image of Person",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300215302",
              "type": "Type",
              "_label": "Digital Image"
            }
          ],
          "format": "image/jpeg",
          "access_point": [
            {
              "id": "http://example.org/egperson/image.jpg",
              "type": "DigitalObject"
            }
          ]
        }
      ]
    }
  ]
}`

**Comment by azaroth42** [comment]
Fixed
