### ISSUE TITLE
schema absolute path

### ISSUE THREAD

**Issue by paulgirard** [linked-art/json-validator#5]
The schema files have some local absolute path in their ids.
This does not ease their use in other context then this local set-up.

I changed locally in my machine the ids to simply the schema file names:

![image](https://user-images.githubusercontent.com/193478/172844724-18f432c0-c52d-4d03-a4fb-acbb1ade20ef.png)

To later indicate the absolute path context in the base_uri parameter of a RefResolver to set up the validator:

```python
def get_validator(schema_filepath: str) -> Draft7Validator:
    with open(schema_filepath, "r") as f:
        return Draft7Validator(
            schema=json.load(f),
            resolver=RefResolver(
                base_uri=f"file://{os.path.dirname(os.path.abspath(schema_filepath))}/",
                referrer={},
            ),
        )

person_validator = get_validator("model/linked-art-schema/schema/person.json")
place_validator = get_validator("model/linked-art-schema/schema/place.json")
activity_validator = get_validator("model/linked-art-schema/schema/event.json")
```
Don't you think such a mechanism would ease the use of the schemas?
If yes I can do a PR with the modifications plus an example of use.
Let me know what you think.

**Comment by paulgirard** [comment]
Note: such a change would open the way to do automatic schema validation for the examples in github actions.

**Comment by azaroth42** [comment]
Fixed by moving to URLs
